//#import "Basic";

//#import "Strings|modules/onelivesleft/jai-string/v1.0.8/";
//Test :: #import "TestModule|";

//#import "Plot";
//#import "Strings";
//width : s32 : 800;
//height : s32 : 600;

short :: "a short \rstring";
long :: #string __
a
long
string
__

main :: () {
    write_string(short);
    write_string("\n");
    write_string(long);
    write_string("\n");
  //  print("%\n", Test.foo);
    //for word: split("Hello world", #char " ")
    //    print("%\n", word);

//    plot_start(width, height);
//
//    block(100, 100, 700, 500, colors.red);
//    disc(width/2, height/2, 100, colors.yellow);
//    circle(width/2, height/2, 100, colors.cyan);
//
//    plot_done();
}
